DROP TABLE CUSTOMERS_INFO;
CREATE TABLE CUSTOMERS_INFO(ID BIGINT PRIMARY KEY AUTO_INCREMENT, 
                  NAME VARCHAR(30), ADDRESS VARCHAR(100), VIN VARCHAR(30), REGNO VARCHAR(10), STATUS VARCHAR(20));